### ISSUE TITLE
Integrate metric_fu

### ISSUE THREAD

**Issue by dkubb** [mbj/devtools#10]
It looks like metric_fu https://github.com/metricfu/metric_fu is in active development again, and is now working in 1.8 *and* 1.9 mode. The reason we stopped using it originally was because it did not work in 1.9.

I would like to see if metric_fu can be integrated so that it will execute as part of rake ci process. The artifacts can also be published to S3 if we wanted: http://about.travis-ci.org/blog/2012-12-18-travis-artifacts/

**Comment by mbj** [comment]
As this is very old I'll close this issue.
