### ISSUE TITLE
Mutant config should allow specifying rationals

### ISSUE THREAD

**Issue by backus** [mbj/devtools#113]
Before https://github.com/mbj/devtools/commit/ac80555b868182b404993aeff4893b57785f5856 I could write my mutant config like this

```yaml
---
name: my_lib
namespace: MyLib
expect_coverage: 495/750
```

but now it rejects values which are not floats.  This is a pretty big pain for projects which are not yet at 100% mutation coverage.  I think we should update this to allow string values so that this previous behavior works.  We could coerce using `Rational()` after mutant's config is loaded if we want to guarantee that it is the proper rational representation. 

I'm happy to fix this myself tonight.

**Comment by mbj** [comment]
Coercing floats into rationals is not a good idea.

What you want is using `Rational()` on the string value that will go loveless.
