### ISSUE TITLE
travis config file

### ISSUE THREAD

**Issue by solnic** [mbj/devtools#19]
Devtools could help in distributing and maintaining travis config files. WDYT? /cc @dkubb @mbj @snusnu

**Comment by mbj** [comment]
I removed travis from all my gems as its to slow compared to Circle. Also I reduced the matrix significantly to one or 2 ruby implementations. Reducing the scope to what I use by mself is in-line with my meanwhile changed OSS policy that states: I only make myself and the projects I work on happy.
