### ISSUE TITLE
Help install less gems on travis for projects using devtools

### ISSUE THREAD

**Issue by bf4** [mbj/devtools#49]
In your .travis.yml you have

```yaml
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
```

This is because you don't need, for ci, all the gems that devtools provides. However, the naive user of devtools may not know to add this and will end up installing too many gems.

I'm not sure the best implementation of solving this, either documentation, or a post install message, or a travis.yml check, or all.

In [metric_fu](https://github.com/metricfu/metric_fu/blob/master/.travis.yml) I use

```yaml
bundler_args: --without local_development yard metrics guard --path vendor/bundle
cache: bundler # not part of this issue, but tmyk
```
(It would be really nice if devtools had a general bundle group for everything it includes)

Thoughts?

**Comment by mbj** [comment]
Devtools changed meanwhile and runs all of the included gems on CI. Closing.
