### ISSUE TITLE
Tiny naming change

### ISSUE THREAD

**Issue by moonglum** [mbj/devtools#51]
Currently we have the metrics task available under the `ci` namespace. The metrics tasks themselves are under the `metrics` namespace as a top level namespace. For example:

```
rake ci
rake ci:metrics
rake metrics:reek
```

This is a tiny thing – but it makes me sad :wink: I would prefer to have the following:

```
# Version 1:
rake ci
rake metrics
rake metrics:reek

# Version 2:
rake ci
rake ci:metrics
rake ci:metrics:reek
```

I prefer the first version, because otherwise `spec` would have to be in `ci` as well. Are you okay with the change to Version 1?

**Comment by mbj** [comment]
I doubt this will happen. My plan is to drop `rake` dependency anyways soon.
