### ISSUE TITLE
Bootstrapping after git clone?

### ISSUE THREAD

**Issue by mvz** [mbj/devtools#61]
Hi, I'm trying to run `bundle install` on my local clone of https://github.com/mbj/unparser, a project that uses devtools. I'm running into the problem that this fetches current devtools master and then bombs out because unparser depends on older versions of rake, etc. than devtools. From devtools' README, I gather that the update process involves `bundle exec devtools sync`. However, since `bundle install` won't run, I'm left hand-modifying Gemfile.devtools.

Is there a better way, and if so, what is it?

**Comment by mbj** [comment]
We totally changed installation, do not need the `Gemfile.devtools` anymore etc. Also devtools now has a gem release. Closing this issue.
