### ISSUE TITLE
Make reek, coveralls and simplecov(?) optional

### ISSUE THREAD

**Issue by snusnu** [mbj/devtools#63]
IMO these could also live inside a `Gemfile(.devtools)`. I find myself rarely using `reek` recently, I don't see much point in `coveralls` and with `mutant`'s coverage expectation configuration setting, I don't need `simplecov` either. Dropping the hard dependencies on those would cut down `bundle` time also.

**Comment by mbj** [comment]
This gem is very opinionated, I'll not introduce options. Sorry.
