### ISSUE TITLE
Rubocop deprecation warnings

### ISSUE THREAD

**Issue by jsuchal** [mbj/devtools#64]
Hi there!

I am getting 
```
.../config/rubocop.yml - AllCops/Excludes was renamed to AllCops/Exclude
.../config/rubocop.yml - AllCops/Includes was renamed to AllCops/Include
Warning: unrecognized cop EmptyLinesAroundBody found in .../config/rubocop.yml
```

The first two are trivial the last one is probably linked to 
https://github.com/bbatsov/rubocop/pull/1399 where the cop was separated into 3 distinct cops. Any preference on defaults before I submit PR?

**Comment by mbj** [comment]
This was all fixed meanwhile due various updates. Sorry for late reaction, closing.
