### ISSUE TITLE
Upgrade to Reek 3

### ISSUE THREAD

**Issue by backus** [mbj/devtools#73]
Reek version 3 was released about two weeks ago https://github.com/troessner/reek/releases

One change they made was to move all of their wiki pages into the main repo, so now the `--wiki-links` flag is useless.  This gem doesn't use the wiki links flag, but devtools does make it impossible to upgrade to Reek 3 since it looks the dependency at 2.

**Comment by mbj** [comment]
@backus Can you submit a PR?

**Comment by backus** [comment]
Sure thing I'll look into it later today

**Comment by mbj** [comment]
Cool. Thx.

**Comment by backus** [comment]
Closed by #74
